#!/usr/bin/env php
<?php
require_once(dirname(__FILE__) . '/vendor/noonat/pecs/lib/pecs.php');
require_once(dirname(__FILE__) . '/lib/mochaformatter.php');

$testDir = './tests';

if ($handle = opendir($testDir)) {

	while (false !== ($entry = readdir($handle))) {
		if (preg_match("/.*\.php$/sim", $entry)) {
			require_once($testDir . '/' . $entry);
		}
	}
}

\pecs\run(new \pecs\MochaFormatter(array('growl' => true)));
