#!/usr/bin/env php
<?php
// Make sure we don't time out
set_time_limit(0);

// Include the testing libraries
try {
	include_once(dirname(__FILE__) . '/vendor/noonat/pecs/lib/pecs.php');
} catch (Exception $e) {
	include_once(dirname(__FILE__) . '/../../noonat/pecs/lib/pecs.php');
}

include_once(dirname(__FILE__) . '/lib/mochaformatter.php');

// Handle Signals
declare(ticks = 1);
pcntl_signal(SIGTERM, "signal_handler");
pcntl_signal(SIGINT, "signal_handler");
function signal_handler($signal) {
	switch($signal) {
		case SIGTERM:
		case SIGKILL:
		case SIGINT:
			shutdown();
			exit;

		default:
			exit;
	}
}

// Reset the cursor when we quit
function shutdown() {
	stop();
	showCursor();
	echo("\n");
}

// Animation spinny loading things
function frames() {
  $frames = array(
      "  \033[96m◜ \033[90mwatching\033[0m"
    , "  \033[96m◠ \033[90mwatching\033[0m"
    , "  \033[96m◝ \033[90mwatching\033[0m"
    , "  \033[96m◞ \033[90mwatching\033[0m"
    , "  \033[96m◡ \033[90mwatching\033[0m"
    , "  \033[96m◟ \033[90mwatching\033[0m"
  );

  return $frames;
}

// Hide the cursor
function hideCursor() {
	echo "\033[?25l";
}

// Show the cursor
function showCursor() {
	echo "\033[?25h";
}

// Play one pass of the animation
function play($frames, $interval = 100000) {
	foreach ($frames as $frame) {
		usleep($interval);
		echo "\r" . $frame;
	}
}

// Erase the line and Carriage Return
function stop() {
	echo "\033[2K";
}

// Watch the folder for changes
function watch($folder = './tests') {
	static $_cache = array();

	$modified = array();

	clearstatcache();
	if ($handle = opendir($folder)) {

		while (false !== ($entry = readdir($handle))) {
			if (preg_match("/.*\.php$/sim", $entry)) {
				$file = $folder . '/' . $entry;
				$stat = stat($file);

				if (isset($_cache[$file])) {
					$lastStat = $_cache[$file];
					if ($stat['mtime'] > $lastStat['mtime']) {
						$modified[] = $file;
					}
				} else {
					$modified[] = $file;
				}

				$_cache[$file] = $stat;
			}
		}
	}

	return $modified;
}

// Watch folder for changes and then run the tests when stuff changes
function testWatch($folder = './tests') {
	$frames = frames();

	hideCursor();

	while (true) {
		play($frames);
		$modified = watch();
		if ($modified) {
			runTests();
		}
	}

	stop();
	echo("\n");
	showCursor();
}

// Run the tests
function runTests() {
	echo "\n\n";
	$path = dirname(__FILE__) . '/pexeRunner';
	echo `$path`;
}

testWatch();
