#!/usr/bin/env php
<?php
// Make sure we don't time out
set_time_limit(0);

// Include the testing libraries
function safeInclude($filename) {
	if (file_exists($filename)) {
		require_once($filename);
	}
}

safeInclude(dirname(__FILE__) . '/../../noonat/pecs/lib/pecs.php');
safeInclude(dirname(__FILE__) . '/vendor/noonat/pecs/lib/pecs.php');

include_once(dirname(__FILE__) . '/lib/mochaformatter.php');

$testDir = './tests';

if ($handle = opendir($testDir)) {

	while (false !== ($entry = readdir($handle))) {
		if (preg_match("/.*\.php$/sim", $entry)) {
			require_once($testDir . '/' . $entry);
		}
	}
}

\pecs\run(new \pecs\MochaFormatter(array('growl' => true)));
