#!/usr/bin/env php
<?php
// Include the testing libraries
try {
	@include_once(dirname(__FILE__) . '/vendor/noonat/pecs/lib/pecs.php');
} catch (Exception $e) {
	include_once(dirname(__FILE__) . '/../../noonat/pecs/lib/pecs.php');
}

include_once(dirname(__FILE__) . '/lib/mochaformatter.php');

$testDir = './tests';

if ($handle = opendir($testDir)) {

	while (false !== ($entry = readdir($handle))) {
		if (preg_match("/.*\.php$/sim", $entry)) {
			require_once($testDir . '/' . $entry);
		}
	}
}

\pecs\run(new \pecs\MochaFormatter(array('growl' => true)));
